[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
exclude = [".venv", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "UP", "N"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["scripts"]
force-sort-within-sections = true
